version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    container_name: soc_api
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data:ro
    environment:
      - ARTIFACTS_DIR=/app/artifacts
    depends_on:
      - mosquitto

  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: soc_app
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data:ro
    environment:
      - API_URL=http://api:8000
      - DATA_DIR=/app/data
      - ARTIFACTS_DIR=/app/artifacts
    depends_on:
      - api

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
